Repository Lomray-Software/microservices, pull requests merged in 2023-06, with the labels that each got.

#43 feat(permissions): update models and endpoints
  microservices/authorization/migrations/permissions/list/methods/payment-stripe.json
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/src/constants/balance-type.ts
  microservices/payment-stripe/src/entities/customer.ts
  microservices/payment-stripe/src/interfaces/capabilities-status.ts
  microservices/payment-stripe/src/methods/stripe/balance.ts
  microservices/payment-stripe/src/methods/stripe/connect-account-link.ts
  microservices/payment-stripe/src/methods/stripe/connect-account.ts
  microservices/payment-stripe/src/methods/stripe/instant-payout.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#44 fix(payment-stripe): add tslib as peer dep
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
Labels: enhancement

#46 feat (payment-stripe): add service tests
  microservices/payment-stripe/__mocks__/stripe.ts
  microservices/payment-stripe/__tests__/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#47 fix: small handle checkout fix
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: bug

#48 feat (ms-payment-stripe): update card workflow
  microservices/authorization/migrations/permissions/list/methods/payment-stripe.json
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/__mocks__/messages.ts
  microservices/payment-stripe/__tests__/methods/customer/crud-test.ts
  microservices/payment-stripe/__tests__/services/payment-gateway/stripe.ts
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/payment-stripe/src/entities/customer.ts
  microservices/payment-stripe/src/entities/product.ts
  microservices/payment-stripe/src/methods/bank-account/add.ts
  microservices/payment-stripe/src/methods/customer/crud.ts
  microservices/payment-stripe/src/methods/customer/remove.ts
  microservices/payment-stripe/src/methods/index.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#49 feat (payment-stripe): add card
  http-requests/payment-stripe/requests.http
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/src/entities/card.ts
  microservices/payment-stripe/src/methods/card/add.ts
  microservices/payment-stripe/src/services/payment-gateway/abstract.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#50 feat(content): has many expand
  http-requests/content/requests.http
  microservices/content/__mocks__/single-type-view-process.ts
  microservices/content/__tests__/helpers/replace-entities-test.ts
  microservices/content/__tests__/services/single-type-view-process-test.ts
  microservices/content/src/helpers/get-expand-route-properties.ts
  microservices/content/src/helpers/replace-entities.ts
  microservices/content/src/interfaces/component-route.ts
  microservices/content/src/interfaces/expand-route.ts
  microservices/content/src/methods/single-type/view.ts
  microservices/content/src/repositories/component.ts
  microservices/content/src/repositories/single-type.ts
  microservices/content/src/services/single-type-view-process.ts
Labels: enhancement

#52 fix(content): build single-type auth model
  http-requests/requests.http
  microservices/content/src/services/single-type-meta.ts
Labels: enhancement

#53 fix(content): build schema flow
  http-requests/content/requests.http
  microservices/content/__tests__/services/single-type-meta-test.ts
  microservices/content/__tests__/services/single-type-view-process-test.ts
  microservices/content/src/helpers/validators/messages.ts
  microservices/content/src/services/single-type-meta.ts
  microservices/content/src/services/single-type-view-process.ts
Labels: bug, enhancement

#54 fix: small transaction fix and added created and updated fields
  microservices/payment-stripe/migrations/1687121988009-created-fields.ts
  microservices/payment-stripe/src/entities/customer.ts
  microservices/payment-stripe/src/entities/price.ts
  microservices/payment-stripe/src/entities/product.ts
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: bug

#55 feat(payment-stipe): update tests and endpoints
  configs/config.local.json
  http-requests/payment-stripe/requests.http
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/README.md
  microservices/payment-stripe/__mocks__/stripe.ts
  microservices/payment-stripe/__tests__/services/payment-gateway/factory.ts
  microservices/payment-stripe/__tests__/services/payment-gateway/stripe.ts
  microservices/payment-stripe/migrations/1679778151988-init.ts
  microservices/payment-stripe/src/entities/bank-account.ts
  microservices/payment-stripe/src/entities/card.ts
  microservices/payment-stripe/src/methods/customer/create.ts
  microservices/payment-stripe/src/methods/stripe/webhook.ts
  microservices/payment-stripe/src/services/card.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/subscribers/card.ts
Labels: enhancement

#56 feat(bloom): stripe add card stripe
  http-requests/payment-stripe/requests.http
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/src/methods/card/add.ts
  microservices/payment-stripe/src/services/card.ts
  microservices/payment-stripe/src/services/payment-gateway/abstract.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement
