Repository Lomray-Software/microservices, pull requests merged in 2023-12, with the labels that each got.

#119 feat(notification): add exclude users without email
  microservices/notification/__tests__/services/task-handlers/email-all-test.ts
  microservices/notification/__tests__/services/task-handlers/email-group-test.ts
  microservices/notification/__tests__/services/task-handlers/notice-all-test.ts
  microservices/notification/__tests__/services/task/index-test.ts
  microservices/notification/src/services/task-handlers/abstract.ts
  microservices/notification/src/services/task-handlers/email-all.ts
  microservices/notification/src/services/task-handlers/email-group.ts
Labels: enhancement

#120 feat(payment-stripe): add account support phone number
  microservices/payment-stripe/src/entities/customer.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#121 feat(authentication): add token count
  microservices/authentication/src/methods/index.ts
  microservices/authentication/src/methods/token/count.ts
  microservices/authorization/migrations/permissions/list/methods/authentication.json
Labels: enhancement

#125 feat(payment-stripe): add webhook handlers service
  microservices/payment-stripe/migrations/1701685975841-dispute.ts
  microservices/payment-stripe/src/helpers/extract-id-from-stripe-instance.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/webhook-handlers/charge.ts
  microservices/payment-stripe/src/services/webhook-handlers/customer.ts
  microservices/payment-stripe/src/services/webhook-handlers/index.ts
Labels: enhancement

#124 feat(payment-stripe): add dispute events and update configs
  .env
  configs/config.local.json
  microservices/payment-stripe/README.md
  microservices/payment-stripe/__mocks__/config.ts
  microservices/payment-stripe/migrations/1701685975841-dispute.ts
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/payment-stripe/src/constants/index.ts
  microservices/payment-stripe/src/entities/dispute.ts
  microservices/payment-stripe/src/helpers/extract-id-from-stripe-instance.ts
  microservices/payment-stripe/src/interfaces/fees.ts
  microservices/payment-stripe/src/services/calculation.ts
  microservices/payment-stripe/src/services/dispute.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/webhook-handlers/charge.ts
  microservices/payment-stripe/src/services/webhook-handlers/customer.ts
  microservices/payment-stripe/src/services/webhook-handlers/index.ts
Labels: documentation, enhancement

#126 feat(payment-stripe): dispute transaction
  microservices/payment-stripe/migrations/1701787694561-transaction-dispute-relation.ts
  microservices/payment-stripe/migrations/1701791863603-transaction-charge-and-dispute.ts
  microservices/payment-stripe/src/constants/charge-refund-status.ts
  microservices/payment-stripe/src/constants/refund-status.ts
  microservices/payment-stripe/src/constants/stripe-refund-status.ts
  microservices/payment-stripe/src/entities/dispute.ts
  microservices/payment-stripe/src/entities/refund.ts
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/repositories/customer.ts
  microservices/payment-stripe/src/services/calculation.ts
  microservices/payment-stripe/src/services/dispute.ts
  microservices/payment-stripe/src/services/parser.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/transaction.ts
  microservices/payment-stripe/src/services/webhook-handlers/account.ts
  microservices/payment-stripe/src/services/webhook-handlers/application-fee.ts
  microservices/payment-stripe/src/services/webhook-handlers/charge.ts
  microservices/payment-stripe/src/services/webhook-handlers/customer.ts
  microservices/payment-stripe/src/services/webhook-handlers/index.ts
  microservices/payment-stripe/src/services/webhook-handlers/payment-intent.ts
  microservices/payment-stripe/src/services/webhook-handlers/payment-method.ts
  microservices/payment-stripe/src/services/webhook-handlers/setup-intent.ts
  microservices/payment-stripe/src/services/webhook-handlers/transfer.ts
  microservices/payment-stripe/src/subscribers/dispute.ts
Labels: enhancement

#123 feat(payment-stripe): add disputes (chargebacks) and evidences
  .env
  configs/config.local.json
  http-requests/payment-stripe/stripe/endpoints/dashboard-login-link.http
  http-requests/payment-stripe/stripe/workflows/refund.http
  http-requests/payment-stripe/stripe/workflows/tax.http
  http-requests/payment-stripe/stripe/workflows/transaction.http
  microservices/payment-stripe/README.md
  microservices/payment-stripe/__mocks__/config.ts
  microservices/payment-stripe/migrations/1701685975841-dispute.ts
  microservices/payment-stripe/migrations/1701787694561-transaction-dispute-relation.ts
  microservices/payment-stripe/migrations/1701791863603-transaction-charge-and-dispute.ts
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/payment-stripe/src/constants/charge-refund-status.ts
  microservices/payment-stripe/src/constants/dispute-reason.ts
  microservices/payment-stripe/src/constants/dispute-status.ts
  microservices/payment-stripe/src/constants/index.ts
  microservices/payment-stripe/src/constants/refund-status.ts
  microservices/payment-stripe/src/constants/stripe-dispute-reason.ts
  microservices/payment-stripe/src/constants/stripe-dispute-status.ts
  microservices/payment-stripe/src/constants/stripe-refund-status.ts
  microservices/payment-stripe/src/entities/dispute.ts
  microservices/payment-stripe/src/entities/evidence-details.ts
  microservices/payment-stripe/src/entities/refund.ts
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/helpers/extract-id-from-stripe-instance.ts
  microservices/payment-stripe/src/interfaces/fees.ts
  microservices/payment-stripe/src/repositories/customer.ts
  microservices/payment-stripe/src/services/calculation.ts
  microservices/payment-stripe/src/services/dispute.ts
  microservices/payment-stripe/src/services/parser.ts
  microservices/payment-stripe/src/services/payment-gateway/abstract.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/transaction.ts
  microservices/payment-stripe/src/services/webhook-handlers/account.ts
  microservices/payment-stripe/src/services/webhook-handlers/application-fee.ts
  microservices/payment-stripe/src/services/webhook-handlers/charge.ts
  microservices/payment-stripe/src/services/webhook-handlers/customer.ts
  microservices/payment-stripe/src/services/webhook-handlers/index.ts
  microservices/payment-stripe/src/services/webhook-handlers/payment-intent.ts
  microservices/payment-stripe/src/services/webhook-handlers/payment-method.ts
  microservices/payment-stripe/src/services/webhook-handlers/setup-intent.ts
  microservices/payment-stripe/src/services/webhook-handlers/transfer.ts
  microservices/payment-stripe/src/subscribers/dispute.ts
Labels: documentation, enhancement

#129 feat(notification): update notice validators and http requests
  http-requests/notification/notice/endpoints/create.http
  http-requests/notification/notice/endpoints/update.http
  microservices/notification/src/entities/notice.ts
Labels: enhancement

#127 feat(payment-stripe): update dispute params
  .env
  configs/config.local.json
  microservices/payment-stripe/src/constants/index.ts
  microservices/payment-stripe/src/entities/dispute.ts
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/services/dispute.ts
  microservices/payment-stripe/src/services/payment-gateway/factory.ts
  microservices/payment-stripe/src/services/webhook-handlers/charge.ts
Labels: enhancement

#131 feat(payment-stripe): update crud and tests and permissions
  microservices/authorization/migrations/permissions/list/methods/payment-stripe.json
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/__mocks__/dispute.ts
  microservices/payment-stripe/__mocks__/evidence-details.ts
  microservices/payment-stripe/__tests__/methods/dispute/crud-test.ts
  microservices/payment-stripe/__tests__/methods/evidence-details/crud-test.ts
  microservices/payment-stripe/src/methods/dispute/crud.ts
  microservices/payment-stripe/src/methods/evidence-details/crud.ts
  microservices/payment-stripe/src/methods/index.ts
Labels: enhancement

#132 feat(payment-stripe): update handle webhook errors and microservice node process exit
  microservices/payment-stripe/README.md
  microservices/payment-stripe/src/methods/stripe/webhook.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/webhook-handlers/charge.ts
Labels: documentation, enhancement

#133 feat(payment-stripe): update sync transaction stats
  microservices/payment-stripe/__tests__/services/transaction-test.ts
  microservices/payment-stripe/src/services/transaction.ts
Labels: enhancement

#122 feat(users): add active users compute
  http-requests/users/requests.http
  microservices/authentication/package-lock.json
  microservices/authentication/package.json
  microservices/authorization/__mocks__/user-roles.ts
  microservices/authorization/__tests__/services/method-filters-test.ts
  microservices/authorization/migrations/permissions/list/filters.json
  microservices/authorization/migrations/permissions/list/methods/authentication.json
  microservices/authorization/migrations/permissions/list/models/common.json
  microservices/authorization/package-lock.json
  microservices/authorization/package.json
  microservices/authorization/src/entities/filter.ts
  microservices/blog/package-lock.json
  microservices/blog/package.json
  microservices/configuration/package-lock.json
  microservices/configuration/package.json
  microservices/content/package-lock.json
  microservices/content/package.json
  microservices/cron/package-lock.json
  microservices/cron/package.json
  microservices/files/package-lock.json
  microservices/files/package.json
  microservices/gateway/package-lock.json
  microservices/gateway/package.json
  microservices/notification/package-lock.json
  microservices/notification/package.json
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/users/package-lock.json
  microservices/users/package.json
Labels: enhancement

#134 feat: created possibility to make embedded checkout form in stripe
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/src/methods/stripe/create-cart-checkout.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#136 feat(payment-stripe): embedded checkout
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/src/methods/stripe/create-cart-checkout.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#137 fix(payment-stripe): embedded checkout
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: bug

#138 feat: update microservices deps
  microservices/authentication/package-lock.json
  microservices/authentication/package.json
  microservices/authorization/package-lock.json
  microservices/authorization/package.json
  microservices/blog/package-lock.json
  microservices/blog/package.json
  microservices/configuration/package-lock.json
  microservices/configuration/package.json
  microservices/content/package-lock.json
  microservices/content/package.json
  microservices/cron/package-lock.json
  microservices/cron/package.json
  microservices/files/package-lock.json
  microservices/files/package.json
  microservices/gateway/package-lock.json
  microservices/gateway/package.json
  microservices/notification/package-lock.json
  microservices/notification/package.json
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/users/package-lock.json
  microservices/users/package.json
Labels: enhancement

#139 fix: changed checkout cart locale to english
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: bug

#140 feat(payment-stripe): embedded checkout nullable return url
  microservices/payment-stripe/src/methods/stripe/create-cart-checkout.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement
