Repository Lomray-Software/microservices, pull requests merged in 2023-11, with the labels that each got.

#98 feat(payment-stripe): add card issuer and customer billing save
  microservices/payment-stripe/migrations/1698922321013-card-holder-and-issuer-billings.ts
  microservices/payment-stripe/src/entities/card.ts
  microservices/payment-stripe/src/services/card.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#97 feat(payment-stripe): cart
  microservices/authorization/migrations/permissions/list/methods/payment-stripe.json
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/migrations/1698656203251-cart.ts
  microservices/payment-stripe/src/entities/cart-product-price.ts
  microservices/payment-stripe/src/entities/cart.ts
  microservices/payment-stripe/src/methods/cart-product-price/crud.ts
  microservices/payment-stripe/src/methods/cart/crud.ts
  microservices/payment-stripe/src/methods/index.ts
  microservices/payment-stripe/src/methods/stripe/create-cart-checkout.ts
  microservices/payment-stripe/src/services/payment-gateway/abstract.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#99 feat(payment-stripe): add config change setup intent usage
  microservices/payment-stripe/src/config/remote.ts
  microservices/payment-stripe/src/constants/index.ts
  microservices/payment-stripe/src/interfaces/remote-config.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#100 feat(ms-payment-stripe): add card checks, duplication validation and renewal logic
  microservices/payment-stripe/migrations/1699352296715-card-payment-method.ts
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/payment-stripe/src/entities/card.ts
  microservices/payment-stripe/src/repositories/card.ts
  microservices/payment-stripe/src/services/card.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#101 feat(payment-stripe): add card created event for external account card
  microservices/payment-stripe/src/services/card.ts
Labels: enhancement

#102 feat(payment-stripe): add login dashboard link endpoint
  http-requests/payment-stripe/stripe/dashboard-login-link.http
  microservices/authorization/migrations/permissions/list/methods/payment-stripe.json
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/src/methods/index.ts
  microservices/payment-stripe/src/methods/stripe/balance.ts
  microservices/payment-stripe/src/methods/stripe/connect-account-link.ts
  microservices/payment-stripe/src/methods/stripe/connect-account.ts
  microservices/payment-stripe/src/methods/stripe/create-cart-checkout.ts
  microservices/payment-stripe/src/methods/stripe/create-checkout.ts
  microservices/payment-stripe/src/methods/stripe/create-payment-intent.ts
  microservices/payment-stripe/src/methods/stripe/dashboard-login-link.ts
  microservices/payment-stripe/src/methods/stripe/instant-payout.ts
  microservices/payment-stripe/src/methods/stripe/setup-intent.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#103 feat(payment-stripe): sync Stripe dashboard detach card with microservice
  microservices/payment-stripe/src/services/card.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/subscribers/card.ts
Labels: enhancement

#105 feat(payment-stripe): add flexible duplicate cards usage
  .env
  configs/config.local.json
  microservices/payment-stripe/src/config/remote.ts
  microservices/payment-stripe/src/constants/index.ts
  microservices/payment-stripe/src/interfaces/remote-config.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#106 fix(authentication): token renew expiration
  microservices/authentication/__tests__/services/methods/renew-auth-token-test.ts
  microservices/authentication/src/entities/token.ts
  microservices/authentication/src/services/methods/renew-auth-token.ts
Labels: bug

#107 feat(payment-stripe): update transaction data storage, add refund application fee
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/README.md
  microservices/payment-stripe/__tests__/services/payment-gateway/stripe.ts
  microservices/payment-stripe/migrations/1700567137231-transaction-application-fee.ts
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/methods/stripe/payment-intent-fees.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/refund.ts
  microservices/payment-stripe/src/services/transaction.ts
  microservices/payment-stripe/src/subscribers/refund.ts
  microservices/payment-stripe/src/subscribers/transaction.ts
Labels: enhancement

#108 feat(payment-stripe): update collected fees calculation
  microservices/payment-stripe/README.md
  microservices/payment-stripe/migrations/1700583822001-transaction-fees.ts
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/methods/stripe/create-payment-intent.ts
  microservices/payment-stripe/src/services/payment-gateway/abstract.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: documentation, enhancement

#109 feat(payment-stripe): update payment intent reversal, tax
  microservices/payment-stripe/README.md
  microservices/payment-stripe/__mocks__/config.ts
  microservices/payment-stripe/__tests__/services/calculation-test.ts
  microservices/payment-stripe/migrations/1700733245581-transaction-charge.ts
  microservices/payment-stripe/migrations/1700750263639-transaction-tax-refs.ts
  microservices/payment-stripe/package-lock.json
  microservices/payment-stripe/package.json
  microservices/payment-stripe/src/constants/index.ts
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/interfaces/payment-intent-metadata.ts
  microservices/payment-stripe/src/interfaces/taxes.ts
  microservices/payment-stripe/src/services/calculation.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/transaction.ts
  microservices/payment-stripe/src/subscribers/transaction.ts
Labels: documentation, enhancement

#110 feat(payment-stripe): update sync failed payments
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#113 feat(notification): update job tasks output
  .env
  configs/cron.json
  microservices/notification/src/interfaces/handled-counts.ts
  microservices/notification/src/jobs/task/process.ts
  microservices/notification/src/services/task-handlers/abstract.ts
  microservices/notification/src/services/task-handlers/factory.ts
  microservices/notification/src/services/task/process.ts
Labels: enhancement

#112 feat(notification): add task handlers workflow and notice all service
  .env
  configs/cron.json
  http-requests/notification/task/index.http
  microservices/authorization/migrations/permissions/list/methods/notification.json
  microservices/authorization/migrations/permissions/list/models/notification.json
  microservices/notification/migrations/1701182756187-task.ts
  microservices/notification/src/config/start.ts
  microservices/notification/src/constants/task-status.ts
  microservices/notification/src/entities/message.ts
  microservices/notification/src/entities/notice.ts
  microservices/notification/src/entities/task.ts
  microservices/notification/src/interfaces/handled-counts.ts
  microservices/notification/src/jobs/index.ts
  microservices/notification/src/jobs/task/process.ts
  microservices/notification/src/methods/task/crud.ts
  microservices/notification/src/services/task-handlers/abstract.ts
  microservices/notification/src/services/task-handlers/email-all.ts
  microservices/notification/src/services/task-handlers/factory.ts
  microservices/notification/src/services/task-handlers/notice-all.ts
  microservices/notification/src/services/task/index.ts
  microservices/notification/src/services/task/process.ts
  microservices/notification/src/subscribers/notice.ts
  microservices/notification/src/subscribers/task.ts
Labels: enhancement

#114 feat(notification): add task email all and update message validation
  http-requests/notification/task/index.http
  microservices/authorization/migrations/permissions/list/models/notification.json
  microservices/notification/__mocks__/task.ts
  microservices/notification/__tests__/methods/task/crud-test.ts
  microservices/notification/__tests__/services/email-provider/nodemailer-test.ts
  microservices/notification/__tests__/services/task-handlers/abstract-test.ts
  microservices/notification/__tests__/services/task-handlers/factory-test.ts
  microservices/notification/migrations/1701258758976-message-template.ts
  microservices/notification/src/entities/message.ts
  microservices/notification/src/entities/notice.ts
  microservices/notification/src/entities/task.ts
  microservices/notification/src/jobs/task/process.ts
  microservices/notification/src/services/email-provider/abstract.ts
  microservices/notification/src/services/email-provider/nodemailer.ts
  microservices/notification/src/services/task-handlers/abstract.ts
  microservices/notification/src/services/task-handlers/email-all.ts
  microservices/notification/src/services/task-handlers/factory.ts
  microservices/notification/src/services/task-handlers/notice-all.ts
  microservices/notification/src/services/task/index.ts
  microservices/notification/src/services/task/process.ts
Labels: enhancement

#116 feat(notification): add task modes and update task factory tests
  http-requests/notification/task/endpoints/notice.http
  http-requests/notification/task/index.http
  microservices/notification/__mocks__/notice.ts
  microservices/notification/__tests__/services/task-handlers/abstract-test.ts
  microservices/notification/__tests__/services/task-handlers/notice-all-test.ts
  microservices/notification/migrations/1701295119446-task-mode.ts
  microservices/notification/migrations/1701305305692-recipient.ts
  microservices/notification/src/constants/task-mode.ts
  microservices/notification/src/constants/task-type.ts
  microservices/notification/src/entities/message.ts
  microservices/notification/src/entities/notice.ts
  microservices/notification/src/entities/recipient.ts
  microservices/notification/src/entities/task.ts
  microservices/notification/src/services/email-provider/abstract.ts
  microservices/notification/src/services/email-provider/nodemailer.ts
  microservices/notification/src/services/task-handlers/abstract.ts
  microservices/notification/src/services/task-handlers/email-all.ts
  microservices/notification/src/services/task-handlers/email-group.ts
  microservices/notification/src/services/task-handlers/factory.ts
  microservices/notification/src/services/task-handlers/notice-all.ts
  microservices/notification/src/services/task/index.ts
Labels: enhancement

#111 feat(notification): init task entity and notify factory infra
  .env
  .github/workflows/pr-check.yml
  configs/cron.json
  http-requests/notification/task/endpoints/notice.http
  http-requests/notification/task/index.http
  microservices/authorization/migrations/permissions/list/methods/notification.json
  microservices/authorization/migrations/permissions/list/models/notification.json
  microservices/notification/README.md
  microservices/notification/__mocks__/notice.ts
  microservices/notification/__mocks__/task.ts
  microservices/notification/__tests__/methods/task/crud-test.ts
  microservices/notification/__tests__/services/email-provider/nodemailer-test.ts
  microservices/notification/__tests__/services/task-handlers/abstract-test.ts
  microservices/notification/__tests__/services/task-handlers/factory-test.ts
  microservices/notification/__tests__/services/task-handlers/notice-all-test.ts
  microservices/notification/migrations/1701182756187-task.ts
  microservices/notification/migrations/1701258758976-message-template.ts
  microservices/notification/migrations/1701295119446-task-mode.ts
  microservices/notification/migrations/1701305305692-recipient.ts
  microservices/notification/package-lock.json
  microservices/notification/package.json
  microservices/notification/src/config/start.ts
  microservices/notification/src/constants/task-mode.ts
  microservices/notification/src/constants/task-status.ts
  microservices/notification/src/constants/task-type.ts
  microservices/notification/src/entities/message.ts
  microservices/notification/src/entities/notice.ts
  microservices/notification/src/entities/recipient.ts
  microservices/notification/src/entities/task.ts
  microservices/notification/src/interfaces/handled-counts.ts
  microservices/notification/src/jobs/index.ts
  microservices/notification/src/jobs/task/process.ts
  microservices/notification/src/methods/index.ts
  microservices/notification/src/methods/notice/hide-all.ts
  microservices/notification/src/methods/task/crud.ts
  microservices/notification/src/services/email-provider/abstract.ts
  microservices/notification/src/services/email-provider/nodemailer.ts
  microservices/notification/src/services/notice/index.ts
  microservices/notification/src/services/task-handlers/abstract.ts
  microservices/notification/src/services/task-handlers/email-all.ts
  microservices/notification/src/services/task-handlers/email-group.ts
  microservices/notification/src/services/task-handlers/factory.ts
  microservices/notification/src/services/task-handlers/notice-all.ts
  microservices/notification/src/services/task/index.ts
  microservices/notification/src/services/task/process.ts
  microservices/notification/src/subscribers/notice.ts
  microservices/notification/src/subscribers/task.ts
Labels: enhancement
