Repository Lomray-Software/microservices, pull requests merged in 2024-02, with the labels that each got.

#164 fix: added possibility to see prefilled email for the first checkout session
  microservices/authorization/migrations/permissions/list/models/payment-stripe.json
  microservices/payment-stripe/src/methods/stripe/create-cart-checkout.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: bug

#165 feat(payment-stripe): move out payout method type to const
  microservices/payment-stripe/src/constants/payout-method-type.ts
  microservices/payment-stripe/src/methods/stripe/instant-payout.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#167 feat(users): update admin change user password validators
  http-requests/users/requests.http
  microservices/users/src/methods/user/change-password.ts
Labels: enhancement

#168 fix(payment-stripe): card expiration date validator
  microservices/payment-stripe/__tests__/helpers/is-card-expiration-date-valid.ts
  microservices/payment-stripe/src/helpers/is-card-expiration-date-valid.ts
Labels: bug

#169 feat(authorization): increase condition description length
  microservices/authorization/migrations/1707321571830-condition-description-length.ts
  microservices/authorization/src/entities/condition.ts
Labels: enhancement

#146 feat(users): verification code context
  microservices/authorization/migrations/permissions/list/models/users.json
  microservices/users/src/methods/confirm-code/send.ts
  microservices/users/src/methods/user/change-login.ts
  microservices/users/src/methods/user/change-password.ts
  microservices/users/src/methods/user/sign-up.ts
  microservices/users/src/services/confirm/abstract.ts
  microservices/users/src/services/confirm/factory.ts
Labels: enhancement

#170 feat(users): update token clean up selection
  microservices/users/src/repositories/user.ts
Labels: enhancement

#171 feat(payment-stripe): update currency conversions
  microservices/payment-stripe/__tests__/helpers/convert-balance-from-unit.ts
  microservices/payment-stripe/src/helpers/convert-balance-from-unit.ts
Labels: enhancement

#172 feat(payment-stripe): services composition
  microservices/payment-stripe/__tests__/services/calculation-test.ts
  microservices/payment-stripe/__tests__/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/constants/transaction-default-params.ts
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/methods/stripe/payment-intent-fees.ts
  microservices/payment-stripe/src/services/calculation.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/webhook-handlers/charge.ts
  microservices/payment-stripe/src/services/webhook-handlers/payment-intent.ts
Labels: enhancement

#173 docs(payment-stripe): init microservice overview
  microservices/payment-stripe/README.md
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/transaction.ts
Labels: documentation

#174 feat(payment-stripe): update stripe methods privacy
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: enhancement

#176 feat(payment-stripe): update services structure
  microservices/payment-stripe/__tests__/services/calculation-test.ts
  microservices/payment-stripe/src/entities/transaction.ts
  microservices/payment-stripe/src/methods/stripe/payment-intent-fees.ts
  microservices/payment-stripe/src/services/common/calculation.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
  microservices/payment-stripe/src/services/webhook-handlers/index.ts
Labels: enhancement

#175 feat(payment-stripe): update docs
  http-requests/payment-stripe/guides/login-customer-in-express-dashboard.http
  http-requests/payment-stripe/guides/login-customer-in-onboarding.http
  http-requests/payment-stripe/guides/setup-customer-account.http
  http-requests/payment-stripe/guides/setup-customer-payment-method.http
  http-requests/payment-stripe/requests.http
  microservices/payment-stripe/README.md
  microservices/payment-stripe/src/services/common/calculation.ts
  microservices/payment-stripe/src/services/payment-gateway/stripe.ts
Labels: documentation, enhancement
